apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
  selector:
    matchLabels:
      tier: frontend
  replicas: 3