apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: deployment
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
   matchLabels:
     app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: deployment
        resources:
          requests:
            cpu: ".2"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: redis-config
        ports:
        - containerPort: 6379
      volumes:
      - name: data
        emptyDir: {}
      - name: redis-config
        configMap:
          name: redis-config
