apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
  namespace: dvl1987
spec:
  containers:
  - image: busybox
    name: time-check
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    env:
    - name: TIME_FREQ
      valueFrom:
      - configMapRef:
        name: time-config
        key: TIME_FREQ
    volumeMounts:
    - mountPath: /opt/time
      name: log-volume
  volumes:
  - name: log-volume
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
